# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#
default: &default
  adapter: sqlite3
  pool: 5
  timeout: 5000

test:
  <<: *default
  host: db
  adapter: postgresql
  encoding: utf8
  database: levumi2_test
  username: postgres
  password: postgres

development:
  <<: *default
  host: db
  adapter: postgresql
  encoding: utf8
  database: levumi2_dev
  username: postgres
  password: postgres

production:
  <<: *default
  adapter: mysql2
  encoding: utf8
#  host: <%= ENV['DB_HOST'] || 'dbserver'   %>
#  database: <%= ENV['DB_NAME'] || 'rails_devise' %>
#  username: <%= ENV['DB_USER'] || 'root' %>
#  password: <%= ENV['DB_PASSWORD'] || '' %>

staging:
  <<: *default
  adapter: mysql2
  encoding: utf8
  host: <%= ENV['DB_HOST'] || 'dbserver'   %>
  database: <%= ENV['DB_NAME'] || 'rails_devise' %>
  username: <%= ENV['DB_USER'] || 'root' %>
  password: <%= ENV['DB_PASSWORD'] || '' %>
