# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#
default: &default
  adapter: sqlite3
  pool: 5
  timeout: 5000

development:
  <<: *default
  host: db
  adapter: postgresql
  database: levumi2_dev
  pool: 50
  username: postgres
  password: postgres

production:
  <<: *default
  adapter: mysql2
  host: dokku.mysql.levumi2_db
  database: levumi2_db
  encoding: utf8
  username: mysql
  password: 78bec44881219f97
