# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#
default: &default
  adapter: sqlite3
  pool: 5
  timeout: 5000

development:
  <<: *default
  host: db
  adapter: postgresql
  database: levumi2_dev
  pool: 50
  username: postgres
  password: postgres

production:
  <<: *default
  adapter: mysql2
  host: localhost
  url: <%= ENV["mysql2://mysql:levumi2@dokku.mysql.levumidb:3306/dokku.mysql.levumidb"] %>
  database: levumidb
  encoding: utf8
  username: levumi2
  password: <%= Rails.application.credentials.dig(:database, :production, :password) %>
