default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  timeout: 5000

development:
  <<: *default
  host: db
  database: levumi2_dev_small
  username: 'root'
  password: 'password'

production:
  <<: *default

staging:
  <<: *default
